const ADD_TODO = "ADD_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const SET_TODOS = "SET_TODO";
const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
const SHOW_ALL = "SHOW_ALL";
const SHOW_CHECKED = "SHOW_CHECKED";
const SHOW_ACTIVE = "SHOW_ACTIVE";

export {
  ADD_TODO,
  TOGGLE_TODO,
  REMOVE_TODO,
  SET_TODOS,
  SET_VISIBILITY_FILTER,
  SHOW_ALL,
  SHOW_CHECKED,
  SHOW_ACTIVE,
};
